#include "definitions.INC"

MODULE STRUCTS
USE MPI
IMPLICIT NONE

! ------------------------------------------------------------------------------------------

TYPE MOLECULE

INTEGER :: NUCLEI
INTEGER, ALLOCATABLE :: CHARGE(:)
REAL *8, ALLOCATABLE :: RNUC(:,:)

! THE MOLECULE STRUCTURE CONTAINS DATA RELATED TO THE MOLECULE TO DIAGONALIZE.
! AFTER INITIALIZATION, THE MOLECULE IS ADDED TO THE HAMILTONIAN STRUCTURE
! AND IS NO LONGER REFERENCED AFTERWARD.


! NUCLEI = NUMBER OF NUCLEI IN MOLECULE
! CHARGE(1:NUCLEI) = ARRAY OF NUCLEAR CHARGES
! RNUC(1:3,1:NUCLEI) = ARRAY OF NUCLEAR COORDINATES

END TYPE MOLECULE

! ------------------------------------------------------------------------------------------

TYPE PARAMETERS


!! nbig is not nbig in jrj/djh notes
!!  in this program it is alloc dim of tinv
!!  tooth.f90 uses nbig as per jrj/djh notes now
!!  jrj/djh notes NBIG = NSMALL * TFACTOR

INTEGER :: N, NBIG, NSMALL, NN, M, NELEC, NCOR, TFACTOR
REAL *8 :: DELTA, THETA, PI, DELTA_1, DELTA_2
NUMBER :: SCALE
LOGICAL :: VQUAD, NUC_ON_GRID

! THE PARAMETERS STRUCTURE CONTAINS VARIOUS DATA RELATING TO THE GRID AND ARRAY SIZES.

! N = NUMBER OF GRID POINTS PER SIDE PER SPATIAL DIMENSION
! NN = 2*N+1 = NUMBER OF GRID POINTS PER SPATIAL DIMENSION
! NBIG / NSMALL = SPECIFIES GRID SIZE WHEN SOLVING FOR T^-1
! M = NN**3 = NUMBER OF 3D GRID POINTS PER ELECTRON
! NELEC = NUMBER OF ELECTRONS IN MOLECULE
! NCOR = SUMMATION PARAMETER USED IN ONE-ELECTRON POTENTIAL MATVEC
! DELTA = GRID SPACING
! THETA = COMPLEX SCALING ANGLE
! PI = 3.14...
! SCALE = EXP(I*THETA) = COMPLEX SCALE FACTOR
! VQUAD = SPECIFIES WHETHER TO USE QUADRATURE RULE FOR POTENTIAL
! NUC_ON_GRID = SPECIFIES IF ALL NUCLEI ARE LOCATED AT GRID POINTS


END TYPE PARAMETERS

! ------------------------------------------------------------------------------------------

TYPE LANPARAMS

INTEGER :: NUMEIGS, KDIM, CHECK
REAL *8 :: TOL
LOGICAL :: GSORTH, SAVE_VECTORS
NUMBER, ALLOCATABLE :: EIGENVALUES(:)
NUMBER, ALLOCATABLE :: EIGENVECTORS(:,:)
REAL *8, ALLOCATABLE :: RESIDUAL(:)

! THE LANPARAMS STRUCTURE CONTAINS DATA NEEDED FOR THE LANCZOS AND ARNOLDI 
! EIGENSOLVERS.

! NUMEIGS = DESIRED NUMBER OF EIGENVALUES
! KDIM = MAXIMUM KRYLOV DIMENSION
! CHECK = FREQUENCY IN WHICH TO CHECK EIGENVALUES FOR CONVERGENCE
! TOL = ABSOLUTE ERROR TOLERANCE FOR CONVERGEBCE 
! GSORTH = SPECIFIES WHETHER TO USE GRAM-SCHMIDT ORTHOGONALIZATION
! SAVE_VECTORS = SPECIFIES WHETHER TO SAVE THE COMPUTED EIGENVECTORS
! EIGENVALES(1:NUMEIGS) = VECTOR OF EIGENVALUES
! EIGENVECTORS(1:MM,1:NUMEIGS) = MATRIX OF EIGENVECTORS (COLUMNS)
! RESIDUAL(1:NUMEIGS) = VECTOR OF EIGENVALUE RESIDUALS

END TYPE LANPARAMS

! ------------------------------------------------------------------------------------------

TYPE HAMILTONIAN

REAL *8 :: ESHIFT
REAL *8, ALLOCATABLE :: TINV(:,:,:)
NUMBER, ALLOCATABLE :: T(:,:), V(:)
TYPE(MOLECULE) :: MOL

! THE HAMILTONIAN STRUCTURE CONTAINS THE ARRAYS NEEDED TO PERFORM THE MATVEC OPERATION.

! ESHIFT = CONSTANT ENERGY FROM NUCLEI-NUCLEI REPULSION (ADDED TO TOTAL ENERGY AT THE END)
! TINV(-NBIG:NBIG,-NBIG:NBIG,-NBIG:NBIG) = MATRIX ELEMENTS OF KINETIC ENERGY INVERSE
! T(1:NN,1:NN) = 1D KINETIC ENERGY MATRIX
! V(1:MM) = POTENTIAL ENERGY MATIRX ELEMEMTS
! MOL = MOLECULE THAT HAMILTONIAN REPRESENTS

END TYPE HAMILTONIAN

! ------------------------------------------------------------------------------------------

TYPE MPI_DATA

INTEGER :: ME, NP, MPISIZE, COMM, STATUS(MPI_STATUS_SIZE)
INTEGER :: MBLK, MAXBLOCK, FIRST, LAST, MM
INTEGER, ALLOCATABLE :: BLOCKS(:), LOW(:), HIGH(:), DISPLS(:)
REAL *8 :: COMM_TIME

! THE MPI_DATA STRUCTURE CONTAINS ALL INFORMATION PERTAINING TO MPI PARALLELIZATION.

! 
! don't we need a variable for M**(NELEC-1) here???  do we have it? -djh
!    alternatively M and NELEC could be here, but neither are

! ME = MPI PROCESS RANK
! NP = NUMBER OF MPI PROCESSES
! MPISIZE = DEFINES DATATYPE SIZE (REAL OR COMPLEX)
! COMM = MPI COMMUNICATOR
! STATUS = MPI STATUS ARRAY
! MBLK = BLOCK SIZE ON PROCESS OF LAST INDEX     what does OF LAST INDEX mean
! MAXBLOCK = MAXIMUM BLOCK SIZE (= MBLK ON ROOT PROCESS)
! FIRST = ABSOLUTE INDEX OF WHERE LOCAL BLOCK STARTS
! LAST = ABSOLUTE INDEX OF WHERE LOCAL BLOCK ENDS
! MM = MBLK*M**(NELEC-1) = TOTAL BLOCK SIZE ON PROCESS
! BLOCKS(1:NP) = ARRAY OF BLOCK SIZES
! DISPLS(1:NP) = DISPLACEMENTS OF BLOCKS USED IN COLLECTIVE GATHER/SCATTER OPERATIONS
! COMM_TIME = KEEPS TRACK OF COMMUNICATION TIME FOR PROFILING PURPOSES

END TYPE MPI_DATA

! ------------------------------------------------------------------------------------------

TYPE GMRES_SOLVER

INTEGER :: MAX_INNER_ITER, MAXRST
INTEGER :: ITER, PCFLAG, PCOPT, ERRFLAG, IUNIT, usepetscflag=1
REAL *8 :: ERR, TOL
NUMBER :: SHIFT

! THE GMRES_SOLVER STRUCTURE CONTAINS DATA REQUIRED TO CALL THE GMRES SOLVER ROUTINE.

!! djh:   max_inner_iter is iterations for (H-E)^-1.  
!!       ( preconditioning is (arguably) counterproductive with GPLHR.
!!           unless preconditioner is fast.  No need for accuracy. )
!!        PCOPT=0 hardwire (GM_PCOPT now parameter set to 0)

! MAX_INNER_ITER = MAXIMUM NUMBER OF INNER GMRES ITERATIONS BEFORE RESTART

! MAXRST = MAXIMUM NUMBER OF RESTARTS ALLOWED
! ITER = NUMBER OF ITERATIONS REQUIRED FOR CONVERGENCE
! PCFLAG = SPECIFIES LEFT (-1), RIGHT (1) OR NO (0) PRECONDITIONING
! PCOPT = SPECIFIES WHICH PRECONDITIONER TO USE
! ERRFLAG = CONTAINS ERROR CODE, SEE DGMRES.F FOR DETAILS
! ERR = FINAL RESIDUAL
! TOL = SPCEIFIED CONVERGENCE CRITERIA: ERR < TOL ==> CONVERGED
! SHIFT = INITIAL ESTIMATE OF DESIRED EIGENVALUE

END TYPE GMRES_SOLVER

! ------------------------------------------------------------------------------------------

TYPE CONTOUR

! NOT IN USE

INTEGER :: N,NN
COMPLEX *16, ALLOCATABLE :: Z(:), JACB(:)
COMPLEX *16, ALLOCATABLE :: Z_DUAL(:), JACB_DUAL(:)

END TYPE CONTOUR

! ------------------------------------------------------------------------------------------

TYPE SPARSE

! NOT IN USE

INTEGER :: M, N, NNZ
INTEGER, ALLOCATABLE :: IA(:), JA(:)
NUMBER, ALLOCATABLE :: HA(:)

END TYPE SPARSE

! ------------------------------------------------------------------------------------------

END MODULE STRUCTS
